name: Deploy Frontend to Pages

on:
  push:
    branches: [ main ] # Dispara o deploy sempre que você der push na main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend # Aqui dizemos ao GitHub para publicar SÓ esta pasta
          branch: gh-pages # O conteúdo vai para essa branch invisível
