name: Deploy Frontend to Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend # Define que os comandos rodam dentro da pasta frontend

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🏗️
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/dist # O Vite coloca o resultado final nesta pasta
          branch: gh-pages
